export const SLS_ACCOUNTS_COLUMNS = {
  id: 'id',
  pv_MultipleUser: 'pv_MultipleUser',
  pv_Administrator: 'pv_Administrator',
  pv_AccountLocked: 'pv_AccountLocked',
  nc_PersonNameCommentText: 'nc_PersonNameCommentText',
  nc_PersonGivenName: 'nc_PersonGivenName',
  nc_PersonMiddleName: 'nc_PersonMiddleName',
  nc_PersonSurName: 'nc_PersonSurName',
  nc_PersonWorkLocation: 'nc_PersonWorkLocation',
  pv_OfficePhone: 'pv_OfficePhone',
  pv_MobilePhone: 'pv_MobilePhone',
  nc_OrganizationSubUnit: 'nc_OrganizationSubUnit',
  nc_EmployeeSupervisor: 'nc_EmployeeSupervisor',
  nc_OrganizationUnitName: 'nc_OrganizationUnitName',
  mo_IdentificationUUID: 'mo_IdentificationUUID',
  realm: 'realm',
  username: 'username',
  email: 'email',
  emailVerified: 'emailVerified',
  status: 'status',
  created: 'created',
  lastUpdated: 'lastUpdated',
  pv_Config: 'pv_Config',
  pv_DomainID: 'pv_DomainID',
  pvVoid: 'pvVoid',
  groups: 'groups',
  administrator: 'administrator',
  name: 'name',
  pv_CanSendBlastMessage: 'pv_CanSendBlastMessage',
  // pvFirstAccountLockedDateTime: 'pvFirstAccountLockedDateTime',
  pvLastLogin: 'pvLastLogin',
};

export const GROUPS_COLUMNS = {
  pvGroupID: 'pvGroupID',
  pvGroupName: 'pvGroupName',
  pvGroupTitle: 'pvGroupTitle',
  pvGroupComment: 'pvGroupComment',
  pvVoid: 'pvVoid',
  pvParentGroupID: 'pvParentGroupID',
  pvDomainID: 'pvDomainID',
  pvIsAgency: 'pvIsAgency',
  pvParentGroupName: 'pvParentGroupName',
  pvParentGroupTitle: 'pvParentGroupTitle',
  pvParentGroupComment: 'pvParentGroupComment',
  pvParentGroupIsAgency: 'pvParentGroupIsAgency',
};

export const ACCOUNTS2GROUP_VIEW_COLUMNS = {
  pvAccount2GroupID: 'pvAccount2GroupID',
  pvAccountID: 'pvAccountID',
  pvGroupAdmin: 'pvGroupAdmin',
  pvGroupID: 'pvGroupID',
  pvVoid: 'pvVoid',
  pvDomainID: 'pvDomainID',
  pvUserID: 'pvUserID',
  pvGlobalID: 'pvGlobalID',
  pvServiceID: 'pvServiceID',
  pvEntryDate: 'pvEntryDate',
  pvLastName: 'pvLastName',
  pvFirstName: 'pvFirstName',
  pvEmailAddress: 'pvEmailAddress',
  pvUserName: 'pvUserName',
  pvAdministrator: 'pvAdministrator',
  pvParentGroupID: 'pvParentGroupID',
  pvGroupName: 'pvGroupName',
  pvIsAgency: 'pvIsAgency',
};
